all:
  hosts:
    node1-database:
      ansible_host: 172.28.0.20
    node2-database:
      ansible_host: 172.28.0.21
    node3-database:
      ansible_host: 172.28.0.22
  vars:
    ansible_python_interpreter: /usr/bin/python3
    ansible_user: clusterdb
    ansible_become: true
    ansible_become_method: sudo
    ansible_become_password: P@ssw0rd
    ansible_ssh_private_key_file: /root/.ssh/proxmox
    cluster_name: postgresql_cluster
    postgresql_version: "16"
    percona_repo_url: "https://repo.percona.com/apt/percona-release_latest.generic_all.deb"
    etcd_cluster: "node1=http://172.28.0.20:2380,node2=http://172.28.0.21:2380,node3=http://172.28.0.22:2380"
    etcd_cluster_client: "http://172.28.0.20:2379,http://172.28.0.21:2379,http://172.28.0.22:2379"
    pgpool_user: pgpool
    pgpool_password: pgpool_p@ssw0rd
    extensions:
      - pg_stat_monitor
      - pg_repack
      - pg_partman
