- name: Configure Pgpool-II
  template:
    src: pgpool.conf.j2
    dest: /etc/pgpool2/pgpool.conf
  notify:
    - Restart Pgpool-II

- name: Enable and start Pgpool-II service
  systemd:
    name: percona-pgpool2
    enabled: true
    state: started
